Refactor
Topsort/building-blocks pull request #119
Opened 2023-07-26 19:49 UTC by sofiavalenzuelapugh

2023-07-26 20:40 UTC, PabloReszczynski requested changes

2023-07-26 20:40 UTC, PabloReszczynski commented on demo/loader.js
> +// const AUTH_BASE_URL = "https://buildingblocks.api.topsort.ai";
remove these

2023-07-26 20:40 UTC, PabloReszczynski commented on src/components/PromoteProduct.tsx
> +      return dataById;
This can be refactored into it's own, testable function

2023-07-26 20:42 UTC, PabloReszczynski commented
I'm kinda concerned about the amount of `useEffect`s happening at the same time (due to the `dispatch` dependency.
Try to decouple the business logic of the effects into their own functions that don't depend on React.

2023-07-28 13:15 UTC, PabloReszczynski requested changes

2023-07-28 13:15 UTC, PabloReszczynski commented on src/components/PromoteProduct.tsx
> +const getProductData = (promoteTargetElements: HTMLElement[]) => {
Here, the arg is not neccesarily a HTMLElement[]. You can create an interface with the data you need

2023-07-28 13:15 UTC, PabloReszczynski commented on src/components/PromoteProduct.tsx
> +        "ts-product-img-url": productImgUrl || "(missing)",
Do not warn inside a reduce. Try to do the printing after the reduction is done. You can even add a new field in the accumulator to store the missing products.

2023-07-31 14:42 UTC, sofiavalenzuelapugh commented on src/components/PromoteProduct.tsx
> +const getProductData = (promoteTargetElements: HTMLElement[]) => {
it is an htlmElement[]
![image](https://github.com/Topsort/building-blocks/assets/95320456/d52b31ec-a9a1-4e91-bf42-4c4943837d2b)

2023-07-31 16:06 UTC, PabloReszczynski commented on src/components/PromoteProduct.tsx
> +const getProductData = (promoteTargetElements: HTMLElement[]) => {
What I mean is that the body of the function doesn't need the parameter to be a `HTMLElement`, just that the objects have the properties `dataset: { tsProductId: string, tsProductName: string, tsProductImgUrl: string }`

2023-07-31 16:07 UTC, PabloReszczynski requested changes

2023-07-31 16:07 UTC, PabloReszczynski commented on src/components/PromoteProduct.tsx
> +      }
Also, don't do any kind of outside mutation inside a reduce as we want it to be a pure function. For this case, you can have the missing attributes as part of the accumulator (`dataById`).

2023-07-31 18:03 UTC, PabloReszczynski approved these changes

2023-07-31 18:04 UTC, merged