Refactor edit inputs
Topsort/building-blocks pull request #131
Opened 2023-08-09 19:04 UTC by sofiavalenzuelapugh

2023-08-11 17:57 UTC, PabloReszczynski requested changes

2023-08-11 17:57 UTC, PabloReszczynski commented on src/components/CampaignDetails/Edit.tsx
> +    return Math.ceil(dayDifference(startDate, new Date()));
Can we test that this value is never negative or NaN?

2023-08-11 21:06 UTC, sofiavalenzuelapugh commented on src/components/CampaignDetails/Edit.tsx
> +    return Math.ceil(dayDifference(startDate, new Date()));
done

2023-08-11 21:13 UTC, PabloReszczynski requested changes
There are a lot of pure functions that can be extracted away from the components to form an "input validation" module, doing that will make unit testing a lot easier.

2023-08-11 21:13 UTC, PabloReszczynski commented on src/components/Input/BudgetInput.tsx
> +    }
This can be put on a separate module and unit tested

2023-08-11 21:13 UTC, PabloReszczynski commented on src/components/Input/BudgetInput.tsx
> +  };
So is this

2023-08-14 19:07 UTC, sofiavalenzuelapugh commented on src/components/Input/BudgetInput.tsx
> +    }
I separated it, but we haven't done any testing on bb yet, should I start rn on later in another pr? with jest?

2023-08-14 19:09 UTC, PabloReszczynski approved these changes

2023-08-14 19:09 UTC, PabloReszczynski commented on src/components/Input/validations.tsx
> +import { Currency } from "@types";
In the future let's add test for this.
Also, since you are not using JSX, the extension of the file could be just .ts

2023-08-14 19:10 UTC, merged